# MD013/line-length - Line length
MD013: false

# MD025/single-title/single-h1 - Multiple top-level headings in the same document
MD025:
  front_matter_title: ""

# MD033 - Inline HTML
MD033:
  allowed_elements: ["img"]

# MD046 - Code block style
MD046:
  style: fenced
